apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: app-dev
  annotations:
    kubernetes.io/change-cause: "session4 - emptyDir로 SQLite DB 저장"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: install-deps
          image: python:3-slim
          command: ["pip", "install", "--target=/deps", "flask", "pyjwt"]
          volumeMounts:
            - name: deps
              mountPath: /deps
      containers:
        - name: auth
          image: python:3-slim
          command: ["python", "/app/auth.py"]
          env:
            - name: PYTHONPATH
              value: /deps
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
            - name: LOG_LEVEL
              value: INFO
            - name: DB_PATH
              value: /data/users.db   # emptyDir에 저장 — Pod 삭제 시 사라짐
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: code
              mountPath: /app
            - name: deps
              mountPath: /deps
            - name: data
              mountPath: /data       # emptyDir 마운트
      volumes:
        - name: code
          configMap:
            name: auth-code
        - name: deps
          emptyDir: {}
        - name: data
          emptyDir: {}               # Pod 단위 임시 스토리지
