apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-data
  namespace: app-dev
spec:
  accessModes:
    - ReadWriteOnce           # 단일 노드에서 읽기/쓰기
  storageClassName: local-path  # Docker Desktop 내장 provisioner
  resources:
    requests:
      storage: 100Mi
