apiVersion: v1
kind: Pod
metadata:
  name: api
  namespace: note-app
  labels:
    app: api
spec:
  containers:
    - name: api
      image: note-api:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
