server {
  listen 80;
  server_name _;

  location / {
    add_header Content-Type text/plain;
    return 200 "web-frontend v1\n";
  }

  location /api/ {
    proxy_pass http://api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /auth/ {
    proxy_pass http://auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}

