apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: note-app
  annotations:
    kubernetes.io/change-cause: "session4: PVC for persistent notes storage"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: python:3-slim
          command: ["sh", "-c"]
          args:
            - "pip install --quiet --no-cache-dir flask && python /app/app.py"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: api-key
            - name: DATA_DIR
              value: "/data"
          volumeMounts:
            - name: code
              mountPath: /app
            - name: data
              mountPath: /data
      volumes:
        - name: code
          configMap:
            name: api-code
        - name: data
          persistentVolumeClaim:
            claimName: api-data
