apiVersion: v1
kind: Pod
metadata:
  name: api
  namespace: app-dev
  labels:
    app: api
    tier: backend
spec:
  containers:
    - name: api
      image: hashicorp/http-echo:latest
      args:
        - "-text=api-ok"
        - "-listen=:8080"
      ports:
        - containerPort: 8080

