apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: app-dev
  labels:
    app: web
    tier: frontend
spec:
  containers:
    - name: web
      image: nginx:alpine
      ports:
        - containerPort: 80

