apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: app-dev
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      port: 80          # Service가 listen하는 포트
      targetPort: 8080  # Pod의 containerPort

