apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: app-dev
  annotations:
    kubernetes.io/change-cause: "auth-v2 text 변경"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        tier: backend
    spec:
      containers:
        - name: auth
          image: hashicorp/http-echo:latest
          args:
            - "-text=auth-v2"
            - "-listen=:8080"
          ports:
            - containerPort: 8080

